Avoid forcibly adding formatted changes to commit and allow the user to re-inspect

diff --git a/bin/git-pre-commit b/bin/git-pre-commit
--- a/bin/git-pre-commit
+++ b/bin/git-pre-commit
@@ -19,9 +19,17 @@
 #   > chmod u+x .git/hooks/pre-commit
 #
 
-for file in `git diff-index --cached --name-only HEAD | grep -E '(code|content|tools)/.*\.(c|cpp|m|h|hpp|java)'` ; do
-  if [ -f $file ]; then
-    clang-format -i ${file}
-    git add ${file}
-  fi
+has_error=0
+
+for file in $(git diff-index --cached --name-only HEAD | grep -E '(code|content|tools)/.*\.(c|cpp|m|h|hpp|java)$'); do
+    if [ -f $file ]; then
+        clang-format --dry-run --Werror -i ${file} 2>/dev/null >/dev/null
+        if [ $? -ne 0 ]; then
+            clang-format -i ${file}
+            echo "Commit aborted due to code format inconsistencies. Source re-formatted, please review and update commit as required."
+            has_error=1
+        fi
+    fi
 done
+
+exit ${has_error}
